// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYGwXk0pSuOuUY82L9Yvu6PuSBR2UHP8U',
    appId: '1:180424116104:android:24dd932f40df24870a5c3d',
    messagingSenderId: '180424116104',
    projectId: 'velora-f0bb0',
    storageBucket: 'velora-f0bb0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLAGuRmjxqsd1MMRMxZOoSwPGq0L0yLyI',
    appId: '1:180424116104:ios:83f8184115172ced0a5c3d',
    messagingSenderId: '180424116104',
    projectId: 'velora-f0bb0',
    storageBucket: 'velora-f0bb0.firebasestorage.app',
    iosBundleId: 'com.example.velora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLAGuRmjxqsd1MMRMxZOoSwPGq0L0yLyI',
    appId: '1:180424116104:ios:83f8184115172ced0a5c3d',
    messagingSenderId: '180424116104',
    projectId: 'velora-f0bb0',
    storageBucket: 'velora-f0bb0.firebasestorage.app',
    iosBundleId: 'com.example.velora',
  );
}
